name: PowerShell Var
description: Tests power shell env vars

inputs:
  environment:
    required: true
    description: Running environment

runs:
  using: composite

  steps:
    - name: Passing var to script
      shell: pwsh
      run: ${{ github.action_path }}/pscript.ps1
      env:
        TARGET_ENV: ${{ inputs.environment }}
        SHOULD_START_TRIGGERS: ${{inputs.environment == 'prd'}}
        ACTION_PATH: ${{github.action_path}}