name: Conditional jobs

on:
  push:

env:
  DEPLOY_CD: 'datafactory,infra,databricks,synapse'

jobs:
  build-config:
    runs-on: ubuntu-latest
    #outputs:
    #  build-infra: ${{steps.build-infra.outputs.build-infra}}
    
    steps:
      - run: |
            if [[ "${{env.DEPLOY_CD}}" == *"infra"* ]]; then
              echo "Should build infra"
            fi


  build-infra:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Building Infra"

  build-databricks:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Building Databricks"