name: Conditional jobs

on:
  push:

env:
  DEPLOY_CD: 'datafactory,infra,databricks,synapse'

jobs:
  build-config:
    runs-on: ubuntu-latest
    outputs:
     build-infra: ${{steps.should-build-infra.outputs.build-infra}}
     build-datafactory: ${{steps.should-build-datafactory.outputs.build-datafactory}}
     build-databricks: ${{steps.should-build-databricks.outputs.build-databricks}}
     build-synapse: ${{steps.should-build-synapse.outputs.build-synapse}}
    
    steps:
      - id: should-build-infra
        run: |
            if [[ "${{env.DEPLOY_CD}}" == *"infra"* ]]; then
              echo "::set-output name=build-infra::true"
            fi

      - id: should-build-datafactory
        run: |
            if [[ "${{env.DEPLOY_CD}}" == *"datafactory"* ]]; then
              echo "::set-output name=build-datafactory::true"
            fi
      - id: should-build-databricks
        run: |
            if [[ "${{env.DEPLOY_CD}}" == *"databricks"* ]]; then
              echo "::set-output name=build-databricks::true"
            fi

      - id: should-build-synapse
        run: |
            if [[ "${{env.DEPLOY_CD}}" == *"synapse"* ]]; then
              echo "::set-output name=build-synapse::true"
            fi

  echo-configs:
    runs-on: ubuntu-latest
    needs:
      - build-config

    steps:
      - run: |
            echo ${{needs.build-config.outputs.build-infra}}
            echo ${{needs.build-config.outputs.build-datafactory}}
            echo ${{needs.build-config.outputs.build-databricks}}
            echo ${{needs.build-config.outputs.build-synapse}}
            
  # build-infra:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - run: echo "Building Infra"

  # build-databricks:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - run: echo "Building Databricks"

  