name: Deploy Package

on:
  workflow_dispatch:
      
  repository_dispatch:
    types:
      - dataops-deployment-approved

  
jobs:
  deploy:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-20.04
    environment: ${{ github.event.client_payload.environment }}
    env:
      artifactUrl: ${{ github.event.client_payload.artifact }}
      environment: ${{ github.event.client_payload.environment }}

    steps:
      - run: echo "Deploying ${{ env.artifactUrl }} to ${{ env.environment }}...."

      - run: echo "Deployment complete to subscription ${{secrets.AZ_SUBSCRIPTION_ID}}"