name: Deploy Package

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - deploy-dev
      - deploy-hlg
      - deploy-prd

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - run: echo "Deploying ${{ github.event.client_payload.artifact }} to ${{ github.event.client_payload.environment }}...."

      - run: echo "Deployment complete"