name: Deploy Package

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - deploy-dev
      - deploy-hlg
      - deploy-prd

jobs:
  deploy:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-20.04
    environment: ${{ github.event.client_payload.environment }}

    steps:
      - run: echo "Deploying ${{ github.event.client_payload.artifact }} to ${{ github.event.client_payload.environment }}...."

      - run: echo "Deployment complete to subscription ${{secrets.AZ_SUBSCRIPTION_ID}} ${{jobs.deploy.environment}}"