name: Deploy Package

on:
  workflow_dispatch:
    inputs:
      artifactUrl:
        description: Url to the artifact to be deployed
        required: true
      environment: 
        description: environment to witch deploy the artifact
        required: true

      
  repository_dispatch:
    types:
      - dataops-deployment-approved

  
jobs:
  deploy:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-20.04
    environment: ${{ github.event.client_payload.environment }}
    env:
      artifactUrl: ${{ github.event.client_payload.artifact }}
      environment: ${{ github.event.client_payload.environment }}

    steps:
      - run: echo "Deploying ${{ env.artifactUrl }} to ${{ env.environment }}...."

      - run: echo "Deployment complete to subscription ${{secrets.AZ_SUBSCRIPTION_ID}}"