name: Test Workflow

on:
  push:

env:
  environment: prd

jobs:
    firstjob:
      runs-on: ubuntu-latest

      steps:

      - uses: actions/checkout@v2

      - name: Run PowerShell Script
        uses: ./.github/actions/powershell-env
        with:
          environment: ${{env.environment}}